language: go
go:
  - tip
  - 1.4.2
  - 1.3.3
  - 1.2.2

# let us have pretty, fast Docker-based Travis workers!
sudo: false

install:
  - go get -d ./...
  - go get golang.org/x/tools/cmd/vet

script:
  - go test -v ./...
  - go vet ./...
